name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular Project
        run: npm run build -- --output-path=dist  # Ensure correct path

      - name: Disable Jekyll
        run: touch dist/.nojekyll  # Prevents GitHub Pages from treating it as a Jekyll project

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout deploy || git checkout --orphan deploy
          rm -rf *
          cp -r dist/* .
          git add .
          git commit -m "Deploy Angular site [CI]"
          git push --force origin deploy