name: Deploy Angular Build to Deploy Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for branch switching

      # Step 2: Install Node.js and dependencies and build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Add detailed logging to see what's happening
      - name: Show package.json build script
        run: cat package.json | grep build
        
      - name: Build Angular App
        run: npm run build --if-present
      
      # More detailed debugging steps
      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la dist || echo "No dist directory"
          find . -type d -name "dist*" || echo "No dist directories found"
          find . -type d | grep -i dist

      # Step 3: Checkout the deploy branch (create if it doesn't exist)
      - name: Checkout deploy branch
        run: |
          git fetch origin deploy || true
          git checkout deploy || git checkout -b deploy

      # Step 4: Copy build files into the deploy branch
      - name: Copy build files
        run: |
          rm -rf *  # Remove existing files to avoid stale files
          
          # Find the build output directory, wherever it is
          BUILD_DIR=$(find .. -type d -path "*/dist*" | head -1)
          
          if [ -n "$BUILD_DIR" ]; then
            echo "Found build directory at: $BUILD_DIR"
            cp -r $BUILD_DIR/* . || echo "Failed to copy from $BUILD_DIR"
          else
            echo "No build directory found!"
            exit 1
          fi
          
          ls -la  # List copied files for debugging

      # Step 5: Commit and push the changes
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy latest build from main branch" || echo "No changes to commit"
          git push origin deploy --force