name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Main Branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to switch branches

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x  # Use the correct version for your project

      - name: Install Dependencies
        run: npm ci  # Ensures a clean install of dependencies

      - name: Build Angular Project
        run: npm run build -- --output-path=dist  # Builds the project and outputs to dist/

      - name: Switch to Deploy Branch
        run: |
          git checkout deploy || git checkout --orphan deploy
          git rm -rf .  # Remove all existing files in deploy branch

      - name: Copy Built Files from Main
        run: |
          git checkout main -- dist/  # Copy only the dist/ folder
          mv dist/wildandbeyond.github.io/browser/* .  # Move contents to root
          rm -rf dist  # Remove the empty dist folder
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy latest build from main [CI]" || echo "No changes to commit"
          git push --force origin deploy
